"""add characters.aliases

Revision ID: 59ef8449f085
Revises: 4e410b0f4eb2
Create Date: 2026-09-26 08:09:48.507313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '59ef8449f085'
down_revision = '4e410b0f4eb2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'aliases')
    # ### end Alembic commands ###
