"""initial schema

Revision ID: 961f54d79f2a
Revises: 
Create Date: 2026-09-11 15:02:32.604799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

revision = '961f54d79f2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # pgvector.sqlalchemy.Vector requires the extension to exist first
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=False),  # keep in sync with shared/nickname-rules.json's maxLength (models/nickname_rules.py) — raising it needs a new migration, not an edit here
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('deletion_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('novels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('fixed_attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mutable_attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('personality', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('novel_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_novel_id'), 'characters', ['novel_id'], unique=False)
    op.create_table('episodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('episode_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('novel_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episodes_novel_id'), 'episodes', ['novel_id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('geo_attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('novel_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_novel_id'), 'locations', ['novel_id'], unique=False)
    op.create_table('relations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_entity_id', sa.UUID(), nullable=False),
    sa.Column('to_entity_id', sa.UUID(), nullable=False),
    sa.Column('entity_kind', sa.String(), nullable=False),
    sa.Column('relation_type', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('novel_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relations_novel_id'), 'relations', ['novel_id'], unique=False)
    op.create_table('story_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('episode_index', sa.Integer(), nullable=False),
    sa.Column('story_timestamp', sa.DateTime(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('novel_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_events_novel_id'), 'story_events', ['novel_id'], unique=False)
    op.create_table('world_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('novel_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_settings_novel_id'), 'world_settings', ['novel_id'], unique=False)
    op.create_table('character_state_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('episode_index', sa.Integer(), nullable=False),
    sa.Column('story_timestamp', sa.DateTime(), nullable=True),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('novel_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_character_state_history_novel_char_episode', 'character_state_history', ['novel_id', 'character_id', 'episode_index'], unique=False)
    op.create_index('ix_character_state_history_novel_char_story_ts', 'character_state_history', ['novel_id', 'character_id', 'story_timestamp'], unique=False)
    op.create_index(op.f('ix_character_state_history_novel_id'), 'character_state_history', ['novel_id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.String(), nullable=False),
    sa.Column('novel_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_novel_id'), 'claims', ['novel_id'], unique=False)
    op.create_table('event_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_event_id', sa.UUID(), nullable=False),
    sa.Column('to_event_id', sa.UUID(), nullable=False),
    sa.Column('link_type', sa.String(), nullable=False),
    sa.Column('branch_reason', sa.Text(), nullable=True),
    sa.Column('novel_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_event_id'], ['story_events.id'], ),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.ForeignKeyConstraint(['to_event_id'], ['story_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_links_novel_from_event', 'event_links', ['novel_id', 'from_event_id'], unique=False)
    op.create_index(op.f('ix_event_links_novel_id'), 'event_links', ['novel_id'], unique=False)
    op.create_index('ix_event_links_novel_to_event', 'event_links', ['novel_id', 'to_event_id'], unique=False)
    op.create_table('event_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('novel_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['story_events.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_locations_novel_id'), 'event_locations', ['novel_id'], unique=False)
    op.create_table('event_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('novel_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['story_events.id'], ),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_participants_novel_id'), 'event_participants', ['novel_id'], unique=False)
    op.create_table('location_state_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('episode_index', sa.Integer(), nullable=False),
    sa.Column('story_timestamp', sa.DateTime(), nullable=True),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('novel_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_state_history_novel_id'), 'location_state_history', ['novel_id'], unique=False)
    op.create_index('ix_location_state_history_novel_loc_episode', 'location_state_history', ['novel_id', 'location_id', 'episode_index'], unique=False)
    op.create_index('ix_location_state_history_novel_loc_story_ts', 'location_state_history', ['novel_id', 'location_id', 'story_timestamp'], unique=False)
    op.create_table('contradiction_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('error_type', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('novel_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contradiction_flags_novel_id'), 'contradiction_flags', ['novel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contradiction_flags_novel_id'), table_name='contradiction_flags')
    op.drop_table('contradiction_flags')
    op.drop_index('ix_location_state_history_novel_loc_story_ts', table_name='location_state_history')
    op.drop_index('ix_location_state_history_novel_loc_episode', table_name='location_state_history')
    op.drop_index(op.f('ix_location_state_history_novel_id'), table_name='location_state_history')
    op.drop_table('location_state_history')
    op.drop_index(op.f('ix_event_participants_novel_id'), table_name='event_participants')
    op.drop_table('event_participants')
    op.drop_index(op.f('ix_event_locations_novel_id'), table_name='event_locations')
    op.drop_table('event_locations')
    op.drop_index('ix_event_links_novel_to_event', table_name='event_links')
    op.drop_index(op.f('ix_event_links_novel_id'), table_name='event_links')
    op.drop_index('ix_event_links_novel_from_event', table_name='event_links')
    op.drop_table('event_links')
    op.drop_index(op.f('ix_claims_novel_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_character_state_history_novel_id'), table_name='character_state_history')
    op.drop_index('ix_character_state_history_novel_char_story_ts', table_name='character_state_history')
    op.drop_index('ix_character_state_history_novel_char_episode', table_name='character_state_history')
    op.drop_table('character_state_history')
    op.drop_index(op.f('ix_world_settings_novel_id'), table_name='world_settings')
    op.drop_table('world_settings')
    op.drop_index(op.f('ix_story_events_novel_id'), table_name='story_events')
    op.drop_table('story_events')
    op.drop_index(op.f('ix_relations_novel_id'), table_name='relations')
    op.drop_table('relations')
    op.drop_index(op.f('ix_locations_novel_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_episodes_novel_id'), table_name='episodes')
    op.drop_table('episodes')
    op.drop_index(op.f('ix_characters_novel_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_table('novels')
    op.drop_table('users')
    # ### end Alembic commands ###
