"""add episodes novel_id episode_index unique constraint

Revision ID: cd25aa9ab9fa
Revises: a3f1c9e2d0b4
Create Date: 2026-09-15 13:21:13.542815

"""
from alembic import op
import sqlalchemy as sa


revision = 'cd25aa9ab9fa'
down_revision = 'a3f1c9e2d0b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_episodes_novel_id_episode_index', 'episodes', ['novel_id', 'episode_index'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_episodes_novel_id_episode_index', 'episodes', type_='unique')
    # ### end Alembic commands ###
