"""add flag_revalidations

Revision ID: d5ee3ddc62cf
Revises: b3c1d9e5f7a2
Create Date: 2026-09-28 00:41:00.342639

"""
from alembic import op
import sqlalchemy as sa


revision = 'd5ee3ddc62cf'
down_revision = 'b3c1d9e5f7a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flag_revalidations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flag_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('setting', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('novel_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flag_id'], ['contradiction_flags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_flag_revalidations_novel_flag_created', 'flag_revalidations', ['novel_id', 'flag_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_flag_revalidations_novel_id'), 'flag_revalidations', ['novel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flag_revalidations_novel_id'), table_name='flag_revalidations')
    op.drop_index('ix_flag_revalidations_novel_flag_created', table_name='flag_revalidations')
    op.drop_table('flag_revalidations')
    # ### end Alembic commands ###
